### PR TITLE
Adds quests 11 and 12

### PR DESCRIPTION
**Pull request by JayH2971**
There's something I'm clearly missing about the pull request process, since I'm quickly accumulating desyncronizations. I tried downloading the current master repository to fork it again on my end, but that doesn't seem to help much. If you have any changes to get us up to speed I'll follow them.

### CODE REVIEW

**Comment by JayH2971** [comment]
Or maybe it'll work now? I'm flying blind, you can tell me if I'm messing things up or doing them right.

**Comment by ajrb** [comment]
Jay, I said that I would sync your fork when you needed me to if you gave me permissions to your repo. I don't think you ever did. Don't worry about getting in a mess with git - I'm a developer and I get tangled up with it every time I try and do anything new. :-)

Looks like you re-forked or something, it's difficult to tell and this PR is not auto merge-able due to conflicts. The first thing I'd like to correct is the files at the root folder of the rep. Duplicates of the 2 new quests as well as the questlist. Also a quests.code-workspace file which I don't want.

Also I thought there were bugfixes for earlier quests - that's what I remember from a notification I got yesterday.

Anyway, not sure where to go from here. I think I can incorporate the 2 new quests into my repo and cancel this PR, and go from there. Don't want to lose your bugfixes though. Unfortunately I don't understand what you did with the re-fork so I cannot fix it. 

Can you give me a bit more info and then I will take a look tomorrow night.  Cheers - and don't worry about it, I spent the first month of my DFU contributing career having major double commit issues due to sync problems until I figured out how to avoid it.

**Comment by JayH2971** [comment]
I think I actually fixed it. I think? It says there are no conflicts with the base branch now. Do you remember whether you gave me instructions on how to permit autosync? If you can point me to them I'll do that and we can save ourselves a lot of trouble.

**Comment by ajrb** [comment]
Nope is not fixed. Still has duplicate files and doesn't have the updates to existing quests. Closing this PR and going to try to apply the previous one. If I can't then I will do a manual commit of the new quests into my repo and we will go from there.

**Comment by JayH2971** [comment]
Sounds good, thanks for working through this with me.

**Pull request closed without merging**
